restful:
  host: 0.0.0.0
  port: 8080
  static_files: 'static-files/potential-license-plate'
logging:
  logging_folder: 'log'
  logging_filename: license-plate-detection.log
detection:
    static_files: 'static-files/detected-license-plate'


